import test from 'node:test';
import assert from 'node:assert/strict';
import {parseFeed,mergeEvents,inferAssets,canonical} from '../evidence-feeds.mjs';
const now=Date.parse('2026-09-21T00:00:00Z'),feed={name:'Example',category:'Macro'};
const item=(link,date='Sun, 20 Sep 2026 10:00:00 GMT')=>`<item><title>Microsoft earnings</title><link>${link}</link><pubDate>${date}</pubDate><description><![CDATA[<p>Reported update</p>]]></description></item>`;
test('RSS parses source provenance and excludes invalid dates, future records and unsafe URLs',()=>{const events=parseFeed(`<rss><channel>${item('https://example.com/a')}${item('javascript:alert(1)')}${item('https://example.com/future','Tue, 22 Sep 2026 10:00:00 GMT')}${item('https://example.com/no','not a date')}</channel></rss>`,feed,now);assert.equal(events.length,1);assert.equal(events[0].sourceName,'Example');assert.equal(events[0].summary,'Reported update');assert.deepEqual(events[0].assets,['MSFT']);});
test('dedup removes tracking parameters, preserves distinct articles and sorts publication time',()=>{const a={source:'https://example.com/a?utm_source=x',publishedAt:'2026-09-20T00:00:00Z'},b={source:'https://example.com/b',publishedAt:'2026-09-20T01:00:00Z'};const all=mergeEvents([[a],[{...a,source:'https://example.com/a'},b]],now);assert.equal(all.length,2);assert.equal(all[0].source,b.source);assert.equal(canonical('data:text/html,test'),null);});
test('Atom selects alternate article URLs and asset mapping does not invent macro exposure',()=>{const a=parseFeed('<feed><entry><title>Fed meeting</title><link rel="self" href="https://example.com/self"/><link rel="alternate" href="https://example.com/article"/><updated>2026-09-20T00:00:00Z</updated></entry></feed>',feed,now);assert.equal(a[0].source,'https://example.com/article');assert.deepEqual(a[0].assets,[]);assert.deepEqual(inferAssets('Microsoft and Nvidia'),['NVDA','MSFT']);});
test('DTD and HTML error pages are rejected instead of reported as healthy feeds',()=>{assert.throws(()=>parseFeed('<!DOCTYPE x><rss/>',feed,now));assert.throws(()=>parseFeed('<html>denied</html>',feed,now));});
