import test from 'node:test';
import assert from 'node:assert/strict';
import {demoConfig,parseBriefInput,reserveDemo,stoneBrief} from '../stone-brief.mjs';
test('Challenge preserves the original assumption baseline even when model output proposes replacements',async()=>{
 const fetchOriginal=globalThis.fetch;
 const baseline={createdAt:'2026-09-20T00:00:00Z',assumptions:[{id:'0',text:'Original demand assumption',invalidation:'Orders decline'}]};
 try{globalThis.fetch=async(url,options)=>{
  if(String(url).endsWith('/chat/completions')){const request=JSON.parse(options.body);assert.ok(!request.messages[0].content.includes('separate assumptions array'));assert.ok(request.messages[1].content.includes('Original demand assumption'));return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({verdict:'Needs checking',checks:[{title:'Support',body:'Conditional demand growth',type:'hypothesis',evidenceIds:[]},{title:'Opposition',body:'Demand may weaken',type:'counterpoint',evidenceIds:[]}],missing:[],assumptions:[{text:'Replacement belief'}]})}}]})};}
  return {ok:true,json:async()=>({code:'00000',data:[],items:[]}),text:async()=>'<rss><channel/></rss>'};
 };const result=await stoneBrief({idea:'Nvidia AI demand grows',action:'challenge',baseline,modelConfig:{provider:'qwen',model:'qwen-plus',apiKey:'test-key-only'}});
 assert.deepEqual(result.assumptions,baseline.assumptions);assert.equal(result.createdAt,baseline.createdAt);
 }finally{globalThis.fetch=fetchOriginal;}
});
test('quick brief extracts familiar company aliases and asks for unknown ticker',()=>{assert.equal(parseBriefInput({idea:'我认为 Tesla 的 Robotaxi 前景被低估'}).symbol,'TSLA');assert.equal(parseBriefInput({idea:'Microsoft AI spending remains strong'}).symbol,'MSFT');assert.throws(()=>parseBriefInput({idea:'我觉得价格跌多了'}),/TICKER_REQUIRED/);assert.throws(()=>parseBriefInput({idea:'x'.repeat(2001)}),/IDEA_LENGTH/);});
test('public demo requires a dedicated key, ignoring unrelated legacy credentials',()=>{assert.equal(demoConfig({DASHSCOPE_API_KEY:'legacy-key'}).configured,false);assert.equal(demoConfig({ASKSTONE_DEMO_QWEN_KEY:'dedicated-key',ASKSTONE_DEMO_QWEN_REGION:'intl'}).provider,'qwen-intl');});
test('daily quota fails closed and atomically bounds per-IP and global attempts',async()=>{const counters=new Map();const db={prepare(sql){let args;return {bind(...v){args=v;return this;},async run(){},async first(){const [key,,limit]=args;const count=counters.get(key)||0;if(count>=limit)return null;counters.set(key,count+1);return {used:count+1};}};}};const now=Date.parse('2026-09-21T12:00:00Z');await assert.rejects(()=>reserveDemo(db,null,now),/LIMIT_UNAVAILABLE/);for(let i=0;i<15;i++)await reserveDemo(db,'ip-a',now);await assert.rejects(()=>reserveDemo(db,'ip-a',now),/DAILY_LIMIT/);for(let i=0;i<285;i++)await reserveDemo(db,'ip-'+i,now);await assert.rejects(()=>reserveDemo(db,'another',now),/DAILY_LIMIT/);assert.equal(counters.get('2026-09-21:global'),300);assert.ok([...counters.keys()].every(k=>!k.includes('ip-a')));});
test('quota is reserved before upstream retrieval; unavailable AI is never silently replaced',async()=>{await assert.rejects(()=>stoneBrief({idea:'Nvidia demand remains strong',action:'challenge',baseline:{createdAt:new Date().toISOString(),assumptions:[{id:'0',text:'Demand grows'}]}},{}),/AI_NOT_CONFIGURED/);await assert.rejects(()=>stoneBrief({idea:'Nvidia demand remains strong'},{ASKSTONE_DEMO_QWEN_KEY:'dedicated-key'},async()=>{throw Error('QUOTA_SENTINEL');}),/QUOTA_SENTINEL/);});
