import React,{useState} from 'react';
import {readDecision,planText} from './decision.mjs';
export function DecisionPlan({event,lang,onUse}){
 const t=(zh,en)=>lang==='en'?en:zh,key='afterbell.plan.'+event.id;
 const [draft,setDraft]=useState(()=>readDecision(localStorage,key)),[saved,setSaved]=useState('');
 const fields=[['horizon',t('观察周期','Time horizon'),t('例如：未来 24 小时／下次美股开盘','e.g. next 24 hours / next US opening')],['trigger',t('什么发生时才考虑行动？','What would trigger action?'),t('写下具体事件或价格条件','Specify an event or price condition')],['invalidation',t('什么证据会推翻你的判断？','What would invalidate your thesis?'),t('例如：官方澄清、关键条件未满足','e.g. official clarification or a failed condition')],['risk',t('最多愿意承担多少损失？','Maximum acceptable loss?'),t('自行填写金额或比例，不会自动下单','Your amount or percentage; no orders are placed')]];
 function update(k,v){setDraft(d=>({...d,[k]:v}));setSaved('');}
 function save(){try{localStorage.setItem(key,JSON.stringify(draft));setSaved(t('研究计划已保存到此浏览器','Plan saved in this browser'));}catch{setSaved(t('保存失败，请复制保留','Storage unavailable; copy your plan'));}}
 return <section className="decision-plan"><div className="section-head"><div><h2>{t('把观点变成可检验的计划','Make your thesis testable')}</h2><p>{t('条件越具体，反证和后续复盘越有意义。','Specific conditions make challenges and reviews more useful.')}</p></div></div><div className="plan-fields">{fields.map(([k,label,placeholder])=><label key={k}>{label}<input maxLength={300} value={draft[k]||''} placeholder={placeholder} onChange={e=>update(k,e.target.value)}/></label>)}</div><label>{t('研究笔记','Research notes')}<textarea maxLength={2000} value={draft.notes||''} onChange={e=>update('notes',e.target.value)} placeholder={t('记录已核实事实、相反证据与尚待确认的内容','Record verified facts, counter-evidence and open questions')}/></label><div className="report-actions"><button onClick={save}>{t('保存计划','Save plan')}</button><button disabled={!draft.trigger||!draft.invalidation} onClick={()=>onUse(planText(draft,lang))}>{t('用这份计划检查观点','Challenge this plan')}</button></div><p className="small">{t('计划只保存在本机；点击检查后会加入研究问题，所选 AI 服务商可收到这些内容。','Plans stay in this browser. Challenging adds them to your research question; your selected AI provider may receive them.')}</p>{saved&&<p role="status">{saved}</p>}</section>;
}
export function ReviewNote({id,lang}){const key='afterbell.review.'+id,t=(zh,en)=>lang==='en'?en:zh;const [d,setD]=useState(()=>readDecision(localStorage,key)),[status,setStatus]=useState('');return <details className="review-note"><summary>{t('记录后续结果与复盘','Record an outcome and review')}</summary><label>{t('复盘状态','Review status')}<select value={d.review||'pending'} onChange={e=>{setD({...d,review:e.target.value});setStatus('');}}><option value="pending">{t('等待验证','Awaiting evidence')}</option><option value="supported">{t('部分证据支持','Some supporting evidence')}</option><option value="invalidated">{t('假设已被推翻','Thesis invalidated')}</option><option value="inconclusive">{t('仍无法判断','Inconclusive')}</option></select></label><textarea aria-label={t('复盘笔记','Review notes')} maxLength={2000} value={d.notes||''} onChange={e=>{setD({...d,notes:e.target.value});setStatus('');}} placeholder={t('后来发生了什么？哪些证据改变了你的判断？','What happened next? Which evidence changed your view?')}/><button onClick={()=>{try{localStorage.setItem(key,JSON.stringify(d));setStatus(t('复盘已保存','Review saved'));}catch{setStatus(t('本地存储不可用','Local storage unavailable'));}}}>{t('保存复盘','Save review')}</button><small role="status">{status}</small><p>{t('这是你的人工复盘，不是收益统计或模型准确率。','This is your manual review, not a performance or accuracy statistic.')}</p></details>;}
