import {Experience} from './Experience.jsx';
import {BitgetPanel} from './BitgetPanel.jsx';
import {UserModelSetup} from './UserModelSetup.jsx';
import {ReasoningDesk} from './ReasoningDesk.jsx';
import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {scenarios,symbols,basis,stress} from './research.mjs';
import './style.css';
import {readJournal,saveRecord,filterEvents,JOURNAL_KEY} from './journal.mjs';
import {ResearchToolbar,EnginePicker,EvidenceList,JournalPanel} from './Workbench.jsx';
import {localizeTree,reportMarkdown} from './i18n.mjs';
const Arrow=()=> <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>;
function Icon({i}){return <svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4">{i===0?<><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><circle cx="12" cy="12" r="1"/></>:i===1?<><path d="M5 3h10l4 4v14H5zM9 11h6M9 15h6M14 3v5h5"/></>:i===2?<path d="M5 20v-7m7 7V7m7 13V2"/>:i===3?<path d="m3 18 6-8 5 4 7-10m-6 0h6v6"/>:<path d="M3 8h18v13H3zM8 8V4h8v4M3 13h18"/>}</svg>}
const money=x=>x==null?'—':new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(x);
function App(){const [lang,setLang]=useState(()=>{try{return localStorage.getItem('afterbell.language')==='en'?'en':'zh';}catch{return 'zh';}});
 useEffect(()=>{document.documentElement.lang=lang==='en'?'en':'zh-CN';try{localStorage.setItem('afterbell.language',lang);}catch{}},[lang]);
 const [page,setPage]=useState(()=>['Radar','Event','Asset','Edge','Portfolio','Sources','Journal','Market','Capsules'].find(p=>p.toLowerCase()===location.hash.slice(1))||'Radar'),[filter,setFilter]=useState('All'),[mode,setMode]=useState('source'),[event,setEvent]=useState({id:'',kind:'unselected',title:'',assets:[],checks:[]}),[news,setNews]=useState(null),[market,setMarket]=useState(null),[loading,setLoading]=useState(false),[thesis,setThesis]=useState(''),[report,setReport]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[asset,setAsset]=useState('NVDA'),[value,setValue]=useState('10000'),[shock,setShock]=useState('-5'),[close,setClose]=useState(''),[token,setToken]=useState(''),[fx,setFx]=useState('1'),[ratio,setRatio]=useState('1');
 const [query,setQuery]=useState(''),[assetFilter,setAssetFilter]=useState('All'),[hours,setHours]=useState(0),[visibleCount,setVisibleCount]=useState(6),[engine,setEngine]=useState('rules'),[config,setConfig]=useState(null),[notice,setNotice]=useState(''),[records,setRecords]=useState(()=>{try{return readJournal(localStorage);}catch{return [];}});
 const [userModel,setUserModel]=useState({provider:'qwen',model:'qwen-plus',apiKey:''});
 const [comparisonPeers,setComparisonPeers]=useState([]);
 const [browserMarket,setBrowserMarket]=useState(null);
 const runId=useRef(0);
 useEffect(()=>{runId.current++;setReport(null);setBusy(false);setNotice('');},[event.id,thesis,engine,userModel]);
 useEffect(()=>{setVisibleCount(6);},[query,assetFilter,hours,filter,mode]);
 const say=(zh,en)=>lang==='en'?en:zh;
 function save(){try{const record={version:1,id:report.createdAt+'-'+event.id,savedAt:new Date().toISOString(),event,report};setRecords(saveRecord(localStorage,record));setNotice(say('已保存到此浏览器','Saved in this browser'));}catch{setNotice(say('保存失败：本地存储不可用或已满','Save failed: local storage unavailable or full'));}}
 function openRecord(r){setEvent(r.event);setThesis(r.report.thesis);navigate('Event');pendingReport.current=r.report;}
 const pendingReport=useRef(null);
 useEffect(()=>{if(pendingReport.current){setReport(pendingReport.current);pendingReport.current=null;}},[event,thesis,page]);
 function removeRecord(id){try{const all=records.filter(r=>r.id!==id);localStorage.setItem(JOURNAL_KEY,JSON.stringify(all));setRecords(all);}catch{setNotice(say('无法修改本地存储','Local storage unavailable'));}}
 const navigate=p=>{setPage(p);history.replaceState(null,'','#'+p.toLowerCase());};
 async function refresh(){setLoading(true);const fetchOne=async(url,set,fallback)=>{try{const r=await fetch(url,{signal:AbortSignal.timeout(25000)});if(!r.ok)throw Error();set(await r.json());}catch{set(fallback);}};await Promise.allSettled([fetchOne('/api/news',setNews,{status:'unavailable',events:[]}),fetchOne('/api/market',setMarket,{status:'unavailable',assets:[]}),fetchOne('/api/health',d=>setConfig(d.ai),{ai:{configured:false}})]);setLoading(false);}
 useEffect(()=>{refresh();},[]);
 const events=mode==='scenario'?scenarios:news?.events||[];
 const filteredEvents=filterEvents(events,{query,category:filter,asset:assetFilter,hours});
 const rows=market?.assets?.length?market.assets:symbols.map(symbol=>({symbol}));
 async function run(e){e.preventDefault();if(!event.id)return;const id=++runId.current;setError('');setBusy(true);setReport(null);try{const r=await fetch('/api/challenge',{method:'POST',signal:AbortSignal.timeout(55000),headers:{'Content-Type':'application/json'},body:JSON.stringify({thesis,eventId:event.id,mode:engine,lang,browserMarket,peerSymbols:comparisonPeers,...(engine==='byok'?{modelConfig:userModel}:{})})});const data=await r.json();if(!r.ok)throw Error(data.error);if(id===runId.current)setReport(data);}catch(e){if(id===runId.current)setError(say('分析未完成，请检查来源或模型配置后重试。','Analysis failed. Check the source or model setup, then retry.')+' ['+e.message+']');}finally{if(id===runId.current)setBusy(false);}}
 async function copyReport(){try{await navigator.clipboard.writeText(reportMarkdown(report,event,lang));setNotice(say('报告已复制','Report copied'));}catch{setNotice(say('请展开报告文本，手动复制。','Expand the report text and copy it manually.'));}}
 function download(){const text=reportMarkdown(report,event,lang);const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='afterbell-research.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const Challenge= <section className="panel challenge"><h2>Challenge My Trade</h2><div className="eyebrow">PRESS A THESIS. GET A WIDER LENS.</div><EnginePicker userModel={userModel} lang={lang} engine={engine} setEngine={setEngine} config={config} onSetup={()=>navigate('Sources')}/>{!event.id&&<p className="selection-hint">{say('先从左侧选择一条事件，再检验你的观点。','Select an event first, then challenge your thesis.')}</p>}<form onSubmit={run}><label className="small" htmlFor="thesis">研究对象：{event.kind==='scenario'?'[演示情景] ':''}<span data-original={event.kind==='source'}>{event.title}</span></label><textarea id="thesis" minLength={10} maxLength={2000} required placeholder="我准备买 NVDA rToken，因为我认为周末跌得太多，下次开盘会反弹。" value={thesis} onChange={e=>setThesis(e.target.value)}/><div className="counter">{thesis.length}/2000</div><button className="primary" disabled={busy||!event.id||thesis.trim().length<10}>{busy?'正在检查假设…':'Stress-test thesis'}<Arrow/></button></form><p className="small">{engine==='byok'?say('我的模型 · 观点与证据发送到所选服务商','My model · Sends thesis and evidence to selected provider'):engine==='qwen'?say('Qwen · 提交观点与所选事件到阿里云','Qwen · Sends thesis and selected event to Alibaba Cloud'):'规则压力测试 · 未使用大模型'}</p>{error&&<p role="alert">{error}</p>}{report?<div className="report" aria-live="polite" data-original={report.mode!=='rules'}><p className="report-meta">{report.mode!=='rules'?(report.provider||'Qwen')+' · '+report.model:say('规则检查','Rule-based')} · {new Date(report.createdAt).toLocaleString(lang==='en'?'en-US':'zh-CN')}</p><h3>{report.verdict}</h3>{report.checks.map((c,i)=><article key={c.title}><span className="accent">0{i+1}</span><h4>{c.title}</h4><p>{c.body}</p>{c.evidenceIds?.length>0&&<small>{c.type} · {c.evidenceIds.join(', ')}</small>}</article>)}<h4>待补证据</h4>{report.missing.map(m=><p key={m}>{m}</p>)}<EvidenceList lang={lang} report={report}/><div className="report-actions"><button onClick={save}>{say('保存研究','Save research')}</button><button onClick={download}>导出研究报告 <Arrow/></button><button onClick={copyReport}>{say('复制报告','Copy report')}</button></div><details className="report-text"><summary>{say('查看完整报告文本','View full report text')}</summary><textarea readOnly aria-label={say('完整报告文本','Full report text')} value={reportMarkdown(report,event,lang)}/></details>{notice&&<p role="status">{notice}</p>}</div>:<div className="closing">Evidence before conviction.</div>}</section>;
 const Table=<section className="panel asset-table"><div className="section-head"><h3>TRACKED ASSETS</h3><button className="link" onClick={()=>navigate('Asset')}>Manage assets <Arrow/></button></div><div className="table-scroll"><table><thead><tr><th>SYMBOL</th><th>UNDERLYING CLOSE</th><th>TOKEN QUOTE</th><th>BASIS</th><th>LAST UPDATED</th></tr></thead><tbody>{rows.slice(0,page==='Radar'?4:6).map(r=><tr key={r.symbol}><td><button className="symbol" onClick={()=>{setAsset(r.symbol);navigate('Asset');}}>{r.symbol}</button></td><td>—</td><td>{money(r.price)} {r.price?r.quoteCurrency:''}</td><td>—</td><td className="muted">{r.quotedAt?`${r.stale?'STALE · ':''}${new Date(r.quotedAt).toLocaleString(lang==='en'?'en-US':'zh-CN')}`:r.snapshotAt?((r.stale?'STALE · ':'')+'快照 '+new Date(r.snapshotAt).toLocaleString(lang==='en'?'en-US':'zh-CN')+' · 成交时间未知'):r.status||'Awaiting verified feed'}</td></tr>)}</tbody></table></div></section>;
 return <Experience setComparisonPeers={setComparisonPeers} report={report} lang={lang} setLang={setLang} page={page} navigate={navigate} events={news?.events||[]} event={event} setEvent={setEvent} loading={loading} refresh={refresh} setThesis={setThesis} records={records} challenge={localizeTree(Challenge,lang)} marketPanel={e=><BitgetPanel key={e.id} event={e} lang={lang} report={report} onSnapshot={setBrowserMarket}/>} reasoning={e=><ReasoningDesk key={e.id} event={e} lang={lang}/>} journal={<JournalPanel lang={lang} records={records} onOpen={openRecord} onRemove={removeRecord}/>} settings={<UserModelSetup lang={lang} value={userModel} onChange={setUserModel} onUse={()=>{setEngine('byok');navigate(event.id?'Event':'Radar');}} onClear={()=>{setUserModel(v=>({...v,apiKey:''}));setEngine('rules');}}/>}/>;
}
createRoot(document.getElementById('root')).render(<App/>);
