import React,{useState,useEffect,useRef} from 'react';
import {StockLogo} from './StockLogo.jsx';
import {ThesisDesk} from './ThesisDesk.jsx';
import {readTheses,THESIS_KEY,candidates} from './thesis-memory.mjs';
import {validSavedReview} from './change-review.mjs';
export function MemoryHome(props){
 const {lang,events,model,onSettings,onCreate}=props,t=(zh,en)=>lang==='en'?en:zh;
 const [book,setBook]=useState(()=>readTheses(localStorage)),[selected,setSelected]=useState(null),[advanced,setAdvanced]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');const ctrl=useRef(null);
 useEffect(()=>()=>ctrl.current?.abort(),[]);
 const active=book.find(b=>b.id===selected),review=active&&validSavedReview(active.changeReview,active.assumptions)?active.changeReview:null;
 const label=s=>({challenged:t('需要关注','Needs attention'),unclear:t('证据不足，无法判断','Unclear'),no_meaningful_change:t('未发现实质变化','No meaningful change')})[s];
 async function check(){setBusy(true);setNotice('');ctrl.current?.abort();const abort=new AbortController();ctrl.current=abort;const target=active;const timer=setTimeout(()=>abort.abort(),90000);try{
  const r=await fetch('/api/changes',{method:'POST',signal:abort.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({idea:target.idea,symbol:target.symbol,createdAt:target.createdAt,assumptions:target.assumptions.map(({id,text,invalidation})=>({id,text,invalidation})),lang,...(model?.apiKey?{modelConfig:model}:{})})});const d=await r.json();if(!r.ok)throw Error(d.error);if(!validSavedReview(d,target.assumptions))throw Error('INVALID_REVIEW');
  const latest=readTheses(localStorage),next=latest.map(b=>b.id===target.id?{...b,changeReview:d,changeReviews:[d,...(Array.isArray(b.changeReviews)?b.changeReviews:[])].slice(0,10)}:b);localStorage.setItem(THESIS_KEY,JSON.stringify(next));setBook(next);
 }catch(e){if(!abort.signal.aborted)setNotice(e.message==='AI_NOT_CONFIGURED'?t('AI 尚未配置：本次没有生成变化结论。可在设置中连接你的模型。','AI is not configured. No change assessment was generated. Connect a model in Settings.'):e.message==='DEMO_DAILY_LIMIT'?t('今日体验额度已用完，可以在设置中使用自己的模型。','Daily demo quota reached. Use your own model in Settings.'):t('检查或保存未完成，请重试；上次结果仍保留。','Check or save failed. Retry; the previous result is preserved.'));else setNotice(t('检查超时，请重试。','Check timed out. Please retry.'));}finally{clearTimeout(timer);setBusy(false);}
 }
 function goBack(){setAdvanced(false);setSelected(null);setNotice('');setBook(readTheses(localStorage));}
 if(advanced&&active)return <><button onClick={()=>{setAdvanced(false);setBook(readTheses(localStorage));}}>{t('← 返回变化摘要','← Back to change summary')}</button><ThesisDesk {...props} initialId={active.id}/></>;
 return <section className="memory-home"><div className="section-head"><div><small>ASKSTONE / MEMORY</small><h1>{active?t('就是这里需要再看一眼。','Here is what deserves another look.'):t('你的理由，后来怎样了？','What happened to your reasons?')}</h1><p>{t('先看变化，再决定是否深入。','See what changed before going deeper.')}</p></div><button disabled={busy} onClick={active?goBack:onCreate}>{active?t('所有记忆','All memories'):t('记录新想法','New idea')}</button></div>
 {!active&&<div className="memory-cards">{book.map(b=>{const r=validSavedReview(b.changeReview,b.assumptions)?b.changeReview:null,needs=r?.results.filter(x=>x.status==='challenged').length||0,newCount=candidates(b,events).filter(e=>Date.now()-Date.parse(e.publishedAt)<=86400000).length;return <article key={b.id}><div className="thesis-symbol"><StockLogo symbol={b.symbol}/><h2>{b.symbol}</h2><small>{b.closed?t('已归档','Archived'):t('我的判断','My thesis')}</small></div><p className="memory-idea">{b.idea}</p><span>{b.assumptions.length} {t('个核心假设','core assumptions')}</span><h3>{r?(needs?t(`${needs} 项需要关注`,`${needs} need attention`):r.results.every(x=>x.status==='no_meaningful_change')?t('本次未发现实质变化','No meaningful change in this check'):t('仍有假设缺少直接证据','Some assumptions lack direct evidence')):t('尚未检查变化','Not checked yet')}</h3><p className="small">{r?`${r.mode==='ai'?'AI':t('来源检查','Feed check')} · ${new Date(r.checkedAt).toLocaleString()}`:t('没有检查过，不代表判断仍然成立。','Not checked does not mean unchanged.')}</p>{newCount>0&&<p className="memory-new">{t(`近 24h 有 ${newCount} 条新线索，影响待核实`,`${newCount} new leads in 24h; impact not assessed`)}</p>}<button onClick={()=>{setSelected(b.id);setNotice('');}}>{t('看看哪里变了','See what changed')} →</button></article>})}{!book.length&&<article><h2>{t('先记住一个真实的想法。','Start with one real idea.')}</h2><p>{t('在 Stone Brief 中点击“记住我的观点”，它就会出现在这里。','Choose Remember my thesis in a Stone Brief to add it here.')}</p><button className="primary" onClick={onCreate}>{t('问 Stone','Ask Stone')}</button></article>}</div>}
 {active&&<article className="memory-review"><span className="thesis-symbol"><StockLogo symbol={active.symbol}/><h2>{active.symbol} · What Changed?</h2></span><p className="memory-idea">“{active.idea}”</p><p className="small">{t('对照保存时的假设，检查此后发布的新证据。','Compare the saved assumptions with evidence published since then.')} · {new Date(active.createdAt).toLocaleString()}</p><button className="primary" disabled={busy} onClick={check}>{busy?t('正在逐条比对新证据…','Comparing each assumption…'):t('检查哪里变了','Check what changed')}</button><p className="small">{t('按需运行；没有后台持续监控。AI 分析使用报道标题与摘要，需查原文核实。','Runs on demand, not in the background. AI assesses reported titles and excerpts; verify the originals.')}</p>
 {notice&&<p role="alert">{notice} <button onClick={onSettings}>{t('模型设置','Model settings')}</button></p>}
 {review?<><div className="memory-outcome"><strong>{review.results.filter(r=>r.status==='challenged').length} / {active.assumptions.length}</strong><span>{t('项假设受到挑战','assumptions challenged')} · {review.results.filter(r=>r.status==='unclear').length} {t('项无法判断','unclear')}</span><small>{review.mode==='ai'?review.provider+' · '+review.model:t('暂无新证据，未调用 AI','No new evidence; no AI call')} · {new Date(review.checkedAt).toLocaleString()}</small></div>{review.results.map(r=>{const a=active.assumptions.find(a=>a.id===r.assumptionId);return <section className="memory-result" key={r.assumptionId}><span className={'review-state state-'+r.status}>{label(r.status)}</span><h3>{a.text}</h3><p>{r.reason}</p>{a.invalidation&&<small>{t('推翻条件：','Invalidated if: ')}{a.invalidation}</small>}<div>{r.evidenceIds.map(id=>{const e=review.evidence.find(e=>e.id===id);return e?<a key={id} href={/^https?:\/\//.test(e.url||'')?e.url:undefined} target="_blank" rel="noreferrer">[{id}] {e.title} ↗</a>:null;})}</div></section>})}<details><summary>{t('本次检查的覆盖范围与历史','Coverage and previous checks')}</summary><p>{t('仅覆盖当前可访问来源近 30 天内、保存时间之后的记录；最多挑选 20 条候选，不能保证没有漏报。','Only available feed records within 30 days and after saving; up to 20 ranked candidates. Coverage is not exhaustive.')}</p><p>{review.coverage?.availableSources??0}/{review.coverage?.totalSources??0} {t('个来源可用','sources available')} · {review.evidence.length} {t('条候选证据','candidate records')}</p>{(Array.isArray(active.changeReviews)?active.changeReviews:[]).slice(1).filter(r=>validSavedReview(r,active.assumptions)).map((r,i)=><p key={i}>{new Date(r.checkedAt).toLocaleString()} · {r.results.filter(x=>x.status==='challenged').length} {t('项需关注','need attention')}</p>)}</details></>:<div className="memory-pending"><h3>{t('准备好后，点一次检查。','When ready, run one check.')}</h3><p>{t('系统会自动检索新证据，逐条解释它是否改变了你的理由。','We retrieve new evidence and explain its implications for each reason.')}</p></div>}
 <details><summary>{t('查看原始假设','Original assumptions')}</summary>{active.assumptions.map(a=><p key={a.id}>{a.text}{a.invalidation&&<small> · {a.invalidation}</small>}</p>)}</details><button disabled={busy} onClick={()=>setAdvanced(true)}>{t('高级复核：手动审计、价格对照与归档','Advanced review: audit, price comparison & archive')}</button></article>}
 {!active&&<details className="memory-legacy"><summary>{t('更多记录','More records')}</summary><button onClick={props.onLibrary}>{t('历史研究与时间胶囊','Research history & capsules')}</button><p>{t('数据只保存在当前浏览器。高级复核中可导出。','Stored in this browser only. Export is available in Advanced review.')}</p></details>}</section>;
}
