import React,{useState,useRef} from 'react';
import {StockLogo} from './StockLogo.jsx';
import {bitgetMarket} from '../bitget.mjs';
import {THESIS_KEY,STATES,splitAssumptions,createThesis,readTheses,health,candidates,recordReview,marketDifference} from './thesis-memory.mjs';
export function ThesisDesk({lang,events,loading,refresh,onChallenge,onLibrary,onCreate,initialId}){
 const t=(zh,en)=>lang==='en'?en:zh;
 const [book,setBook]=useState(()=>readTheses(localStorage)),[selected,setSelected]=useState(initialId||null),[creating,setCreating]=useState(false),[idea,setIdea]=useState(''),[symbol,setSymbol]=useState('NVDA'),[horizon,setHorizon]=useState(''),[draft,setDraft]=useState(null),[notice,setNotice]=useState(''),[review,setReview]=useState({}),[busy,setBusy]=useState(false),[current,setCurrent]=useState(null),[peer,setPeer]=useState('SPY');
 const bookRef=useRef(book);bookRef.current=book;
 const active=book.find(b=>b.id===selected),h=active&&health(active),newEvents=active?candidates(active,events):[];
 const label=s=>({unverified:t('待核实','Unverified'),supported:t('有支持证据','Supported'), 'at-risk':t('受到挑战','At risk'),broken:t('已被推翻','Broken')})[s];
 function persist(next){try{localStorage.setItem(THESIS_KEY,JSON.stringify(next));bookRef.current=next;setBook(next);return true;}catch{setNotice(t('保存失败：浏览器存储不可用或已满。请先导出。','Save failed: browser storage unavailable or full. Export first.'));return false;}}
 function update(next){return persist(bookRef.current.map(b=>b.id===next.id?next:b));}
 function select(b){setSelected(b.id);setCurrent(null);setReview({});setPeer(b.marketBaseline?.peer||'SPY');setCreating(false);setNotice('');}
 function build(e){e.preventDefault();setDraft(splitAssumptions(idea));}
 function save(){try{const b=createThesis({symbol,horizon,idea,assumptions:draft});if(book.length>=50)throw Error('LIBRARY_FULL');if(persist([b,...book])){select(b);setDraft(null);setIdea('');}}catch{setNotice(t('请检查代码、观点和假设；档案最多保存 50 条。','Check ticker, thesis and assumptions; the library holds 50 entries.'));}}
 function exportBook(){const url=URL.createObjectURL(new Blob([JSON.stringify(book,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='askstone-thesis-library.json';a.click();URL.revokeObjectURL(url);}
 async function checkMarket(){setBusy(true);setNotice('');const target=active;try{if(!/^[A-Z0-9.]{1,16}$/.test(peer)||peer===target.symbol)throw Error();const get=async s=>{let d;try{const r=await fetch('/api/bitget?symbol='+s,{signal:AbortSignal.timeout(15000)});d=await r.json();}catch{}if(d?.status!=='ok')d={...await bitgetMarket(s),browserFetched:true};if(!(d.price>0)||!d.quoteTimestamp)throw Error();return {price:d.price,time:Number(d.quoteTimestamp),source:d.source||'Bitget public API',browserFetched:!!d.browserFetched};};const [asset,benchmark]=await Promise.all([get(target.symbol),get(peer)]);const snap={symbol:target.symbol,peer,at:Date.now(),asset,benchmark};if([asset,benchmark].some(q=>Math.abs(snap.at-q.time)>120000))throw Error();setCurrent(snap);if(!target.marketBaseline){update({...bookRef.current.find(b=>b.id===target.id),marketBaseline:snap});setNotice(t('已保存价格基线。稍后刷新后比较相同起点的变化。','Price baseline saved. Refresh later to compare changes from this point.'));}}catch{setNotice(t('缺少新鲜且对齐的有效报价，暂不计算市场分歧。','Fresh aligned quotes unavailable; no disagreement calculated.'));}finally{setBusy(false);}}
 const diff=active&&marketDifference(active.marketBaseline,current);
 return <section className="thesis-desk"><div className="thesis-intro"><div><small>ASKSTONE / DECISION MEMORY</small><h1>{t('价格在变。你的理由还成立吗？','Your position keeps trading. Your thesis should too.')}</h1><p>{t('记住你当初的判断，把新证据与每一个假设对照。','Remember what you believed. Check new evidence against each assumption.')}</p></div><button className="primary" onClick={()=>{if(onCreate){onCreate();return;}setCreating(true);setSelected(null);setDraft(null);}}>{t('建立交易逻辑','Build my thesis')} ↗</button></div>
 <div className="thesis-layout"><aside className="thesis-book"><div className="section-head"><h2>{t('我的逻辑档案','Thesis library')}</h2><span>{book.length}</span></div>{book.length===0?<p>{t('从一个真实的交易理由开始。','Start with one real trading idea.')}</p>:book.map(b=>{const v=health(b),n=candidates(b,events).length;return <button className="thesis-book-item" key={b.id} aria-pressed={b.id===selected} onClick={()=>select(b)}><span className="thesis-symbol"><StockLogo symbol={b.symbol}/><strong>{b.symbol}</strong><small>{b.closed?t('已归档','Archived'):t('跟进中','Open')}</small></span><span>{b.idea.slice(0,90)}</span><small>{v.broken?t(`${v.broken} 项被推翻`,`${v.broken} broken`):v.atRisk?t(`${v.atRisk} 项受挑战`,`${v.atRisk} at risk`):t(`${v.reviewed}/${v.total} 已核实`,`${v.reviewed}/${v.total} reviewed`)} · {n} {t('条新线索','new leads')}</small></button>})}<div className="thesis-tools"><button disabled={!book.length} onClick={exportBook}>{t('导出档案','Export library')}</button><button onClick={onLibrary}>{t('旧研究与时间胶囊','Research & capsules')}</button></div><p className="small">{t('仅保存在当前浏览器。刷新时检查当前新闻源；无后台监控或推送。','Stored in this browser only. Checks the current feed on refresh; no background monitoring or alerts.')}</p></aside>
 <div className="thesis-content">{onCreate&&!book.length&&<div className="thesis-empty"><h2>{t('还没有记住的观点','No saved theses yet')}</h2><p>{t('先向 Stone 说一句你的想法，在简报里点“记住我的观点”。','Tell Stone your idea, then choose Remember my thesis in the brief.')}</p><button className="primary" onClick={onCreate}>{t('问 Stone','Ask Stone')} →</button></div>}{(creating||(!book.length&&!onCreate))&&<form className="thesis-create" onSubmit={build}><small>01 / {t('写下你的判断','WHAT DO YOU BELIEVE?')}</small><h2>{t('先留下理由，再看市场。','Write the reason before watching the price.')}</h2><div className="thesis-fields"><label>{t('标的代码','Ticker')}<input required pattern="[A-Z0-9.]{1,16}" maxLength={16} value={symbol} onChange={e=>setSymbol(e.target.value.toUpperCase())}/></label><label>{t('观察周期','Time horizon')}<input required maxLength={100} value={horizon} onChange={e=>setHorizon(e.target.value)} placeholder={t('例如一个月','e.g. one month')}/></label></div><label>{t('我的交易逻辑（每行一个理由）','My thesis (one reason per line)')}<textarea required minLength={10} maxLength={2000} value={idea} onChange={e=>{setIdea(e.target.value);setDraft(null);}} placeholder={t('我关注 NVDA，因为 AI 基础设施支出持续增长。\n云厂商不会下调资本开支。','I follow NVDA because AI infrastructure spending keeps growing.\nCloud providers will not cut capital expenditure.')}/></label><button className="primary">{t('整理为可核实的假设','Structure my assumptions')}</button>{draft&&<div className="thesis-draft"><p>{t('按句子整理的草稿，未调用 AI。请把每条改成可以被证据推翻的假设；保存后保留原始表述。','Sentence-based draft, not AI extraction. Edit each assumption so evidence can falsify it; saved wording is preserved.')}</p>{draft.map((a,i)=><label key={a.id}>{i+1}<input required maxLength={500} value={a.text} onChange={e=>setDraft(draft.map((x,j)=>j===i?{...x,text:e.target.value}:x))}/></label>)}<button type="button" disabled={draft.some(a=>!a.text.trim())} onClick={save}>{t('确认并保存基线','Confirm & save baseline')}</button></div>}</form>}
 {!active&&!creating&&book.length>0&&<div className="thesis-empty"><h2>{t('下一步：检查你的理由。','Next: revisit your reasons.')}</h2><p>{t('从左侧打开档案，查看新线索和已确认的变化。','Open a thesis to see new leads and confirmed changes.')}</p></div>}
 {active&&<><div className="thesis-detail-head"><span className="thesis-symbol"><StockLogo symbol={active.symbol}/><h2>{active.symbol}</h2></span><span>{active.horizon} · {new Date(active.createdAt).toLocaleString()}</span><button onClick={()=>update({...active,closed:!active.closed})}>{active.closed?t('恢复跟进','Reopen'):t('归档','Archive')}</button></div><p className="original-thesis">“{active.idea}”</p><div className="thesis-health"><div><small>THESIS HEALTH</small><h2>{h.broken?t('核心理由需要重审','Revisit the thesis'):h.atRisk?t('有假设受到挑战','Assumptions at risk'):h.reviewed<h.total?t('证据尚不完整','Evidence incomplete'):t('当前已核实假设有支持','Reviewed assumptions supported')}</h2></div><span><b>{h.reviewed}/{h.total}</b> {t('已核实','reviewed')}</span><span>{h.supported} {t('支持','supported')} · {h.atRisk} {t('受挑战','at risk')} · {h.broken} {t('推翻','broken')}</span></div><p className="small">{t('基于你的证据复核，不是模型置信度、收益预测或健康评分。','Based on your evidence reviews, not model confidence, return forecasts or a numerical health score.')}</p>
 <section className="thesis-changes"><div className="section-head"><div><small>WHAT CHANGED?</small><h2>{t('从建立判断之后','Since your thesis')}</h2></div><button disabled={loading} onClick={refresh}>{loading?t('检查中…','Checking…'):t('刷新证据线索','Refresh evidence')}</button></div><p>{t('新线索按资产关联，不代表支持、反对或因果关系。新闻源可能不完整。','New leads match the asset, not support, contradiction or causality. Feed coverage may be incomplete.')}</p>{newEvents.length===0&&<p>{t('当前来源中没有尚未处理的新线索；不代表你的假设得到验证。','No unreviewed new leads in the current feed; this does not validate the thesis.')}</p>}{newEvents.slice(0,12).map(e=><article className="thesis-lead" key={e.id}><small>{new Date(e.publishedAt).toLocaleString()} · {e.publisher||t('来源记录','Source record')}</small><h3>{e.title}</h3><a href={/^https?:\/\//.test(e.source||'')?e.source:undefined} target="_blank" rel="noreferrer">{t('核实原文','Verify original')} ↗</a><button onClick={()=>onChallenge(active,e)}>{t('Challenge My Thesis · AI 深入核查','Challenge my thesis · AI review')}</button><button onClick={()=>update({...active,seen:[...active.seen,e.id]})}>{t('标记已处理','Mark reviewed')}</button></article>)}</section>
 <section><h2>{t('逐条审计假设','Audit each assumption')}</h2>{active.assumptions.map((a,i)=>{const r=review[a.id]||{};const available=events.filter(e=>e.kind==='source'&&e.assets?.includes(active.symbol));return <details className="assumption" key={a.id}><summary><span>0{i+1} · {a.text}</span><b data-state={a.status}>{label(a.status)}</b></summary><label>{t('选择证据来源','Select evidence')}<select value={r.eventId||''} onChange={e=>setReview({...review,[a.id]:{...r,eventId:e.target.value}})}><option value="">{t('请选择并核实原文','Select and verify a source')}</option>{available.map(e=><option key={e.id} value={e.id}>{e.title}</option>)}</select></label>{r.eventId&&<button onClick={()=>onChallenge(active,available.find(e=>e.id===r.eventId))}>{t('让 AI 挑战这份逻辑','Challenge this thesis with AI')}</button>}{r.eventId&&<a href={/^https?:\/\//.test(available.find(e=>e.id===r.eventId)?.source||'')?available.find(e=>e.id===r.eventId)?.source:undefined} target="_blank" rel="noreferrer">{t('打开原文','Open original')} ↗</a>}<label>{t('复核状态','Reviewed status')}<select value={r.status||a.status} onChange={e=>setReview({...review,[a.id]:{...r,status:e.target.value}})}>{STATES.map(s=><option key={s} value={s}>{label(s)}</option>)}</select></label><label>{t('证据如何改变这条假设？','How does the evidence change this assumption?')}<textarea maxLength={1000} value={r.note||''} onChange={e=>setReview({...review,[a.id]:{...r,note:e.target.value}})}/></label><button disabled={!r.note?.trim()||!r.eventId} onClick={()=>{try{const next=recordReview(active,{assumptionId:a.id,status:r.status||a.status,note:r.note,event:available.find(e=>e.id===r.eventId)});if(update(next))setNotice(t('已保存复核及状态变化。','Evidence review and status change saved.'));}catch{setNotice(t('请选择有效来源并填写理由。','Select a valid source and add a reason.'));}}}>{t('确认复核并记录变化','Confirm review & record change')}</button></details>})}</section>
 <section className="thesis-changes"><small>DECISION MEMORY</small><h2>{t('已确认的变化','Confirmed changes')}</h2>{active.history.length===0?<p>{t('还没有复核记录。每次状态变化都需要来源与理由。','No reviews yet. Every status change requires a source and a reason.')}</p>:active.history.map(x=><article key={x.id} className="thesis-lead"><small>{new Date(x.at).toLocaleString()} · {t('用户确认','User confirmed')}</small><h3>{x.assumption}</h3><b>{label(x.from)} → {label(x.to)}</b><p>{x.note}</p><a href={/^https?:\/\//.test(x.evidence?.source||'')?x.evidence.source:undefined} target="_blank" rel="noreferrer">{x.evidence?.title}</a></article>)}</section>
 <section className="thesis-changes"><small>MARKET DISAGREEMENT</small><h2>{t('价格变化，还是个别资产的变化？','Market-wide move or asset divergence?')}</h2><p>{t('从保存的同一时刻基线比较两个币股的收益差；不等于行业 Beta 调整、定价完成度或事件因果。','Compare two token returns from one saved baseline; not beta adjustment, priced-in probability or event causality.')}</p><label>{t('比较标的','Benchmark ticker')}<input disabled={!!active.marketBaseline||busy} value={peer} maxLength={16} onChange={e=>setPeer(e.target.value.toUpperCase())}/></label><button disabled={busy} onClick={checkMarket}>{busy?t('读取报价…','Fetching quotes…'):active.marketBaseline?t('更新并比较','Refresh & compare'):t('保存价格基线','Save price baseline')}</button>{active.marketBaseline&&<p>{t('价格基线时间','Price baseline')} · {new Date(active.marketBaseline.at).toLocaleString()} · {active.marketBaseline.peer}</p>}{diff?<div className="thesis-health"><span>{active.symbol}<b>{diff.asset.toFixed(2)}%</b></span><span>{current.peer}<b>{diff.benchmark.toFixed(2)}%</b></span><span>{t('收益差','Return difference')}<b>{diff.difference.toFixed(2)} {t('百分点','pp')}</b></span></div>:<p>{t('等待两组更新且时间对齐的报价，不填充估算值。','Waiting for two newer, aligned quotes. No estimated values filled in.')}</p>}</section></>}
 {notice&&<p role="status" className="thesis-notice">{notice}</p>}</div></div></section>;
}
